// <auto-generated />
namespace TP_Autos.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RelationShipBetweenTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationShipBetweenTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202304210354184_RelationShipBetweenTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
